version: '3.8'

services:
  loggerbridge:
    build:
      context: ../   
      dockerfile: package/Dockerfile
    image: package-loggerbridge:a-class
    ports:
      - "5002:5000"
    volumes:
      - ../:/app  
      - ../all_devices.csv:/app/all_devices.csv
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"